### ISSUE TITLE
GitHub URL: Update the GitHub URL Pattern

### ISSUE THREAD

**Issue by gabru-md** [fossasia/open-event-frontend#3324]
**Describe the bug**

I am trying to register as a speaker for an event and, I have to add my GitHub URL in my speaker profile. But it shows that the GitHub URL is invalid. 

**To Reproduce**
Steps to reproduce the behaviour:
1. Register as a speaker for an event on eventyay.com

**Expected behaviour**

Since my profile id `https://github.com/gabru-md` hence it must validate it.

**Screenshots**

![ccpa](https://user-images.githubusercontent.com/25414121/62114004-57a84580-b2d3-11e9-9264-d151f3aa8aa9.PNG)

**Additional context**

cc: @geekyd @mariobehling

**Comment by prateekj117** [comment]
@gabru-md Looking into it.

**Comment by gabru-md** [comment]
sure!

**Comment by kushthedude** [comment]
@gabru-md it would be great of you could help with event name too.

**Comment by kushthedude** [comment]
@gabru-md please write www as you have done in facebook id , should solve the issue

**Comment by gabru-md** [comment]
still shows invalid.
If I input `https://github.com/gabru` then it works.
It fails for `https://github.com/gabru-md`.
![asda](https://user-images.githubusercontent.com/25414121/62119804-00f43900-b2de-11e9-9e03-67b983da70fa.PNG)

**Comment by kushthedude** [comment]
@prateekj117 Can I push its PR, As it is a `priority:high` and you are solving other issues?

**Comment by prateekj117** [comment]
@kushthedude Go ahead.
