### ISSUE TITLE
Organizer Session Page: Dropdown menu results in internal scroll bar

### ISSUE THREAD

**Issue by mariobehling** [fossasia/open-event-frontend#5307]
When an organizer clicks on status pending, accepting etc. in the last row of a page suddenly an internal scroll bar shows up and the dropdown menu appears below other page elements.

Expected: No internal scroll bar. Elements should be on top of below elements.

![Screenshot from 2020-10-14 08-02-37](https://user-images.githubusercontent.com/1583873/95949911-f004ea00-0df3-11eb-9d6d-fd0a3b75a7f5.png)

**Comment by maze-runnar** [comment]
> Expected: No internal scroll bar. Elements should be on top of below elements.

It is showing in that way when it is as the end of wondow not at end of table. Because semantic ui don't work in that way. Because for each cell the dropdown behaviour would be compressed then and be limited to that cell. it shows upside when it is at the end of wondow.
![Screenshot from 2020-10-14 16-11-18](https://user-images.githubusercontent.com/56407566/95978762-3d0aaf80-0e38-11eb-9637-4c351d399fc6.png)

**Comment by abhpd** [comment]
Making `overflow: visible` for `div id="ember1057"` solves the scroll bar issue. But my question is can we do that as the top bar of the table (thead) id="ember1058" is `position: static` and scroll down with the display?
![image](https://user-images.githubusercontent.com/34980034/96361829-b8c17080-1146-11eb-87d7-ecb7f0162665.png)

**Comment by Abhijay007** [comment]
> When an organizer clicks on status pending, accepting etc. in the last row of a page suddenly an internal scroll bar shows up and the dropdown menu appears below other page elements.
> 
> Expected: No internal scroll bar. Elements should be on top of below elements.
> 
> ![Screenshot from 2020-10-14 08-02-37](https://user-images.githubusercontent.com/1583873/95949911-f004ea00-0df3-11eb-9d6d-fd0a3b75a7f5.png)

sir, can you please share the link to the page or location of the file in the codebase.

**Comment by iamareebjamal** [comment]
@mariobehling There are 2 possible solutions:

1. Expand the table from below so the dropdown doesn't get cut
2. Instead of dropdown, a modal popup is shown

**Comment by mariobehling** [comment]
@iamareebjamal I think a pop up is too big of a thing. I saw the screenshot above of @abhpd which looked good, but if that has other issues just extending seems fine, do you think?

![image](https://user-images.githubusercontent.com/34980034/96361829-b8c17080-1146-11eb-87d7-ecb7f0162665.png)

**Comment by iamareebjamal** [comment]
- That'll overflow the table contents, so let's go with table expansion

**Comment by nikolaytoplev** [comment]
I am going on table expansion.

**Comment by nikolaytoplev** [comment]
I implemented table expansion.

**Comment by iamareebjamal** [comment]
The current solution works. But the logic is too complicated. Reopening in hope of a codeheat participant finding a better solution

**Comment by daretobedifferent18** [comment]
@iamareebjamal I think the issue is not yet resolved. 
This is what I am getting same behavious as was before PR was merged
![Screenshot from 2020-12-09 19-35-13](https://user-images.githubusercontent.com/71120226/101639830-c95eda80-3a55-11eb-8199-cfe79d9bbe56.png)

**Comment by iamareebjamal** [comment]
I had to revert the PR because it was caausing other issues

**Comment by abhpd** [comment]
@iamareebjamal @mariobehling I might have a better solution, can you assign it to me?  Thank you.

**Comment by maze-runnar** [comment]
submit a PR

**Comment by rithgan** [comment]
> @iamareebjamal @mariobehling I might have a better solution, can you assign it to me? Thank you.

Are you still working on it?

**Comment by abhpd** [comment]
> > @iamareebjamal @mariobehling I might have a better solution, can you assign it to me? Thank you.
> 
> Are you still working on it?

No.

**Comment by mariobehling** [comment]
Closing it as it will not be an issue in the next version.
